on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
    ubuntu:
      runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
      steps:
      - uses: actions/checkout@v3 
      - name: Set up Python
      uses: actions/setup-python@v3
      with:
        cache: 'pip'
      - name: Install pip dependencies
      run: python -m pip install -r requirements.txt
      - uses: actions/upload-artifact@v3
      with:
          name: pwgui-${{ matrix.os }}
          path: build/