on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Build package
        run: cxfreeze main.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pwgui-${{ matrix.os }}
          path: build/
  
