on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Build package
        run: cxfreeze main.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pwgui-${{ matrix.os }}
          path: build/

  build-windows:
    runs-on: windows-latest 
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Build package
        run: cxfreeze main.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pwgui-${{ matrix.os }}
          path: build/
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Build package
        run: cxfreeze main.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pwgui-${{ matrix.os }}
          path: build/
  
